/**
 * The labs sub-app's reference data: the biomarker catalog ARC seeds, the alias
 * table that maps printed lab names onto it, and the unit-conversion allowlist.
 *
 * All three are curated app-shipped data, not user data. They live here rather
 * than in seed.ts so the mapping layer can import the aliases and conversions
 * without pulling in the whole seeding path.
 *
 * PROVENANCE, AND ITS LIMITS. The ranges below are longevity-oriented targets —
 * deliberately tighter than a lab's population "normal" — assembled from
 * published targets (Attia's stated numbers, Function's optimal tier, standard
 * lab intervals) and then adversarially reviewed for unit errors, inverted
 * direction, and false precision. They are reference lines in a personal tool,
 * NOT diagnosis, treatment, or a substitute for a clinician reading the report.
 * Where a target is genuinely contested (TSH's ceiling, ferritin's, vitamin D's
 * upper end, the LDL floor) a defensible middle was taken.
 *
 * TWO CONVENTIONS THAT ARE LOAD-BEARING:
 *
 *   * **The 12 originally seeded slugs keep their originally seeded values.**
 *     seedReferenceData inserts OR IGNORE, so an existing row is never updated:
 *     changing a value here would only change FRESH installs, silently making
 *     them disagree with a device that has been running since before this file.
 *     Those 12 (apob, ldl_c, hdl_c, triglycerides, lp_a, homocysteine, hs_crp,
 *     hba1c, fasting_glucose, fasting_insulin, vitamin_d, ferritin) are
 *     reproduced exactly, even where newer research would tighten them.
 *     Correcting one is a deliberate migration, not an edit here.
 *
 *   * **Sex-specific ranges are MALE-oriented** (testosterone, estradiol,
 *     ferritin, hemoglobin, hematocrit, RBC, creatinine, ALT, AST, GGT, uric
 *     acid, SHBG, iron, DHEA-S, PSA). ARC is a single-user app whose user is
 *     male (CLAUDE.md). Per-sex ranges would be a schema change, not a data edit.
 *
 * `higherIsBetter` is null far more often than intuition suggests — most markers
 * are U-shaped, harmful at BOTH extremes (ferritin, vitamin D, TSH, sodium,
 * testosterone, IGF-1). Marking one of those 1 or 0 would have the app telling
 * the user "more is better" about something that harms them when high.
 */
import type { BiomarkerCategory } from '@/lib/db/types';

export type BiomarkerSeed = {
  slug: string;
  name: string;
  category: BiomarkerCategory;
  unit: string;
  optimalLow: number | null;
  optimalHigh: number | null;
  higherIsBetter: 0 | 1 | null;
};

/**
 * The catalog ARC ships. A Function Health panel runs ~100-135 rows, so a real
 * report will still introduce markers beyond these — the import creates those
 * as new catalog entries (carrying the lab's own printed range, and no optimal
 * range) rather than dropping their values.
 */
export const BIOMARKER_SEED: BiomarkerSeed[] = [
  {
    slug: 'apob',
    name: 'ApoB',
    category: 'cardiovascular',
    unit: 'mg/dL',
    optimalLow: null,
    optimalHigh: 80,
    higherIsBetter: 0,
  },
  {
    slug: 'ldl_c',
    name: 'LDL Cholesterol',
    category: 'cardiovascular',
    unit: 'mg/dL',
    optimalLow: null,
    optimalHigh: 100,
    higherIsBetter: 0,
  },
  {
    slug: 'hdl_c',
    name: 'HDL Cholesterol',
    category: 'cardiovascular',
    unit: 'mg/dL',
    optimalLow: 50,
    optimalHigh: null,
    higherIsBetter: 1,
  },
  {
    slug: 'triglycerides',
    name: 'Triglycerides',
    category: 'cardiovascular',
    unit: 'mg/dL',
    optimalLow: null,
    optimalHigh: 80,
    higherIsBetter: 0,
  },
  {
    slug: 'total_cholesterol',
    name: 'Total Cholesterol',
    category: 'cardiovascular',
    unit: 'mg/dL',
    optimalLow: 150,
    optimalHigh: 200,
    higherIsBetter: null,
  },
  {
    slug: 'non_hdl_c',
    name: 'Non-HDL Cholesterol',
    category: 'cardiovascular',
    unit: 'mg/dL',
    optimalLow: null,
    optimalHigh: 100,
    higherIsBetter: 0,
  },
  {
    slug: 'lp_a',
    name: 'Lipoprotein(a)',
    category: 'cardiovascular',
    unit: 'nmol/L',
    optimalLow: null,
    optimalHigh: 75,
    higherIsBetter: 0,
  },
  {
    slug: 'ldl_particle_number',
    name: 'LDL Particle Number (LDL-P)',
    category: 'cardiovascular',
    unit: 'nmol/L',
    optimalLow: null,
    optimalHigh: 1000,
    higherIsBetter: 0,
  },
  {
    slug: 'hs_crp',
    name: 'hs-CRP',
    category: 'inflammation',
    unit: 'mg/L',
    optimalLow: null,
    optimalHigh: 1,
    higherIsBetter: 0,
  },
  {
    slug: 'homocysteine',
    name: 'Homocysteine',
    category: 'cardiovascular',
    unit: 'umol/L',
    optimalLow: null,
    optimalHigh: 9,
    higherIsBetter: 0,
  },
  {
    slug: 'fibrinogen',
    name: 'Fibrinogen',
    category: 'inflammation',
    unit: 'mg/dL',
    optimalLow: 200,
    optimalHigh: 350,
    higherIsBetter: null,
  },
  {
    slug: 'fasting_glucose',
    name: 'Fasting Glucose',
    category: 'metabolic',
    unit: 'mg/dL',
    optimalLow: 70,
    optimalHigh: 90,
    higherIsBetter: null,
  },
  {
    slug: 'fasting_insulin',
    name: 'Fasting Insulin',
    category: 'metabolic',
    unit: 'uIU/mL',
    optimalLow: null,
    optimalHigh: 5,
    higherIsBetter: 0,
  },
  {
    slug: 'hba1c',
    name: 'HbA1c',
    category: 'metabolic',
    unit: '%',
    optimalLow: null,
    optimalHigh: 5.4,
    higherIsBetter: 0,
  },
  {
    slug: 'homa_ir',
    name: 'HOMA-IR',
    category: 'metabolic',
    unit: 'index',
    optimalLow: null,
    optimalHigh: 1,
    higherIsBetter: 0,
  },
  {
    slug: 'uric_acid',
    name: 'Uric Acid',
    category: 'metabolic',
    unit: 'mg/dL',
    optimalLow: 3.5,
    optimalHigh: 5.5,
    higherIsBetter: null,
  },
  {
    slug: 'sodium',
    name: 'Sodium',
    category: 'metabolic',
    unit: 'mmol/L',
    optimalLow: 138,
    optimalHigh: 142,
    higherIsBetter: null,
  },
  {
    slug: 'potassium',
    name: 'Potassium',
    category: 'metabolic',
    unit: 'mmol/L',
    optimalLow: 4,
    optimalHigh: 4.5,
    higherIsBetter: null,
  },
  {
    slug: 'chloride',
    name: 'Chloride',
    category: 'metabolic',
    unit: 'mmol/L',
    optimalLow: 98,
    optimalHigh: 104,
    higherIsBetter: null,
  },
  {
    slug: 'co2',
    name: 'CO2 (Bicarbonate)',
    category: 'metabolic',
    unit: 'mmol/L',
    optimalLow: 23,
    optimalHigh: 27,
    higherIsBetter: null,
  },
  {
    slug: 'calcium',
    name: 'Calcium (Total)',
    category: 'metabolic',
    unit: 'mg/dL',
    optimalLow: 9,
    optimalHigh: 10,
    higherIsBetter: null,
  },
  {
    slug: 'phosphorus',
    name: 'Phosphorus',
    category: 'metabolic',
    unit: 'mg/dL',
    optimalLow: 3,
    optimalHigh: 4,
    higherIsBetter: null,
  },
  {
    slug: 'alt',
    name: 'ALT',
    category: 'organ',
    unit: 'U/L',
    optimalLow: 10,
    optimalHigh: 25,
    higherIsBetter: null,
  },
  {
    slug: 'ast',
    name: 'AST',
    category: 'organ',
    unit: 'U/L',
    optimalLow: 10,
    optimalHigh: 25,
    higherIsBetter: null,
  },
  {
    slug: 'ggt',
    name: 'GGT',
    category: 'organ',
    unit: 'U/L',
    optimalLow: 10,
    optimalHigh: 25,
    higherIsBetter: null,
  },
  {
    slug: 'alp',
    name: 'Alkaline Phosphatase',
    category: 'organ',
    unit: 'U/L',
    optimalLow: 40,
    optimalHigh: 80,
    higherIsBetter: null,
  },
  {
    slug: 'bilirubin_total',
    name: 'Total Bilirubin',
    category: 'organ',
    unit: 'mg/dL',
    optimalLow: 0.4,
    optimalHigh: 1,
    higherIsBetter: null,
  },
  {
    slug: 'albumin',
    name: 'Albumin',
    category: 'organ',
    unit: 'g/dL',
    optimalLow: 4.2,
    optimalHigh: 5,
    higherIsBetter: 1,
  },
  {
    slug: 'creatinine',
    name: 'Creatinine',
    category: 'organ',
    unit: 'mg/dL',
    optimalLow: 0.8,
    optimalHigh: 1.1,
    higherIsBetter: null,
  },
  {
    slug: 'egfr',
    name: 'eGFR',
    category: 'organ',
    unit: 'mL/min/1.73m2',
    optimalLow: 90,
    optimalHigh: null,
    higherIsBetter: 1,
  },
  {
    slug: 'bun',
    name: 'BUN',
    category: 'organ',
    unit: 'mg/dL',
    optimalLow: 10,
    optimalHigh: 18,
    higherIsBetter: null,
  },
  {
    slug: 'cystatin_c',
    name: 'Cystatin C',
    category: 'organ',
    unit: 'mg/L',
    optimalLow: 0.6,
    optimalHigh: 0.9,
    higherIsBetter: 0,
  },
  {
    slug: 'wbc',
    name: 'White Blood Cell Count',
    category: 'immune',
    unit: '10^3/uL',
    optimalLow: 3.5,
    optimalHigh: 6,
    higherIsBetter: null,
  },
  {
    slug: 'neutrophils_abs',
    name: 'Neutrophils (Absolute)',
    category: 'immune',
    unit: '10^3/uL',
    optimalLow: 1.8,
    optimalHigh: 4,
    higherIsBetter: null,
  },
  {
    slug: 'lymphocytes_abs',
    name: 'Lymphocytes (Absolute)',
    category: 'immune',
    unit: '10^3/uL',
    optimalLow: 1.5,
    optimalHigh: 3,
    higherIsBetter: null,
  },
  {
    slug: 'neutrophil_lymphocyte_ratio',
    name: 'Neutrophil-to-Lymphocyte Ratio',
    category: 'immune',
    unit: 'ratio',
    optimalLow: null,
    optimalHigh: 2,
    higherIsBetter: 0,
  },
  {
    slug: 'rbc',
    name: 'Red Blood Cell Count',
    category: 'hematology',
    unit: '10^6/uL',
    optimalLow: 4.6,
    optimalHigh: 5.4,
    higherIsBetter: null,
  },
  {
    slug: 'hemoglobin',
    name: 'Hemoglobin',
    category: 'hematology',
    unit: 'g/dL',
    optimalLow: 14,
    optimalHigh: 15.5,
    higherIsBetter: null,
  },
  {
    slug: 'hematocrit',
    name: 'Hematocrit',
    category: 'hematology',
    unit: '%',
    optimalLow: 42,
    optimalHigh: 48,
    higherIsBetter: null,
  },
  {
    slug: 'mcv',
    name: 'MCV',
    category: 'hematology',
    unit: 'fL',
    optimalLow: 85,
    optimalHigh: 92,
    higherIsBetter: null,
  },
  {
    slug: 'rdw',
    name: 'RDW',
    category: 'hematology',
    unit: '%',
    optimalLow: 11.5,
    optimalHigh: 13,
    higherIsBetter: 0,
  },
  {
    slug: 'platelets',
    name: 'Platelet Count',
    category: 'hematology',
    unit: '10^3/uL',
    optimalLow: 175,
    optimalHigh: 250,
    higherIsBetter: null,
  },
  {
    slug: 'tsh',
    name: 'TSH',
    category: 'hormone',
    unit: 'uIU/mL',
    optimalLow: 0.5,
    optimalHigh: 2.5,
    higherIsBetter: null,
  },
  {
    slug: 'free_t3',
    name: 'Free T3',
    category: 'hormone',
    unit: 'pg/mL',
    optimalLow: 3,
    optimalHigh: 3.8,
    higherIsBetter: null,
  },
  {
    slug: 'free_t4',
    name: 'Free T4',
    category: 'hormone',
    unit: 'ng/dL',
    optimalLow: 1,
    optimalHigh: 1.4,
    higherIsBetter: null,
  },
  {
    slug: 'tpo_ab',
    name: 'TPO Antibodies',
    category: 'hormone',
    unit: 'IU/mL',
    optimalLow: null,
    optimalHigh: 9,
    higherIsBetter: 0,
  },
  {
    slug: 'testosterone_total',
    name: 'Testosterone, Total',
    category: 'hormone',
    unit: 'ng/dL',
    optimalLow: 600,
    optimalHigh: 900,
    higherIsBetter: null,
  },
  {
    slug: 'testosterone_free',
    name: 'Testosterone, Free',
    category: 'hormone',
    unit: 'pg/mL',
    optimalLow: 12,
    optimalHigh: 21,
    higherIsBetter: null,
  },
  {
    slug: 'shbg',
    name: 'SHBG',
    category: 'hormone',
    unit: 'nmol/L',
    optimalLow: 20,
    optimalHigh: 45,
    higherIsBetter: null,
  },
  {
    slug: 'estradiol',
    name: 'Estradiol',
    category: 'hormone',
    unit: 'pg/mL',
    optimalLow: 20,
    optimalHigh: 30,
    higherIsBetter: null,
  },
  {
    slug: 'dhea_s',
    name: 'DHEA-S',
    category: 'hormone',
    unit: 'ug/dL',
    optimalLow: 300,
    optimalHigh: 500,
    higherIsBetter: null,
  },
  {
    slug: 'cortisol',
    name: 'Cortisol (AM)',
    category: 'hormone',
    unit: 'ug/dL',
    optimalLow: 8,
    optimalHigh: 15,
    higherIsBetter: null,
  },
  {
    slug: 'igf_1',
    name: 'IGF-1',
    category: 'hormone',
    unit: 'ng/mL',
    optimalLow: 100,
    optimalHigh: 180,
    higherIsBetter: null,
  },
  {
    slug: 'vitamin_d',
    name: 'Vitamin D (25-OH)',
    category: 'nutrient',
    unit: 'ng/mL',
    optimalLow: 40,
    optimalHigh: 60,
    higherIsBetter: null,
  },
  {
    slug: 'vitamin_b12',
    name: 'Vitamin B12',
    category: 'nutrient',
    unit: 'pg/mL',
    optimalLow: 500,
    optimalHigh: 900,
    higherIsBetter: null,
  },
  {
    slug: 'folate',
    name: 'Folate, Serum',
    category: 'nutrient',
    unit: 'ng/mL',
    optimalLow: 10,
    optimalHigh: 24,
    higherIsBetter: null,
  },
  {
    slug: 'magnesium_rbc',
    name: 'Magnesium, RBC',
    category: 'nutrient',
    unit: 'mg/dL',
    optimalLow: 5.2,
    optimalHigh: 6.4,
    higherIsBetter: 1,
  },
  {
    slug: 'omega_3_index',
    name: 'Omega-3 Index',
    category: 'nutrient',
    unit: '%',
    optimalLow: 8,
    optimalHigh: 12,
    higherIsBetter: 1,
  },
  {
    slug: 'ferritin',
    name: 'Ferritin',
    category: 'hematology',
    unit: 'ng/mL',
    optimalLow: 30,
    optimalHigh: 150,
    higherIsBetter: null,
  },
  {
    slug: 'iron',
    name: 'Iron, Total',
    category: 'nutrient',
    unit: 'ug/dL',
    optimalLow: 65,
    optimalHigh: 150,
    higherIsBetter: null,
  },
  {
    slug: 'tibc',
    name: 'TIBC',
    category: 'nutrient',
    unit: 'ug/dL',
    optimalLow: null,
    optimalHigh: null,
    higherIsBetter: null,
  },
  {
    slug: 'transferrin_saturation',
    name: 'Transferrin Saturation',
    category: 'nutrient',
    unit: '%',
    optimalLow: 25,
    optimalHigh: 35,
    higherIsBetter: null,
  },
  {
    slug: 'zinc',
    name: 'Zinc',
    category: 'nutrient',
    unit: 'ug/dL',
    optimalLow: 90,
    optimalHigh: 120,
    higherIsBetter: null,
  },
  {
    slug: 'psa_total',
    name: 'PSA, Total',
    category: 'cancer',
    unit: 'ng/mL',
    optimalLow: null,
    optimalHigh: 2.5,
    higherIsBetter: 0,
  },
  {
    slug: 'biological_age',
    name: 'Biological Age (PhenoAge)',
    category: 'biological_age',
    unit: 'years',
    optimalLow: null,
    optimalHigh: null,
    higherIsBetter: 0,
  },
];

/**
 * Printed-name → slug, keyed by normalizeBiomarkerName's output.
 *
 * Every entry is an EXACT key: the mapper never does substring or fuzzy
 * matching (map.ts explains why). Three properties matter more than the size:
 *
 *   * A bare "CRP" maps to its own `crp` slug, NOT to `hs_crp`. Panels that ran
 *     the high-sensitivity assay sometimes print only "CRP", and guessing wrong
 *     files a result against a marker graded on a different scale.
 *     Unmatched-and-visible beats matched-and-wrong.
 *   * A bare "T3"/"T4" maps to TOTAL, never free — the two differ by roughly
 *     400x in molar terms, so a wrong guess is not a near miss.
 *   * Slugs with no catalog row are kept on purpose. Canonicalizing an unknown
 *     marker means "Reverse T3" and "rT3" create ONE new biomarker instead of
 *     two, and a later seed addition adopts the values already imported.
 *
 * A name claimed by two different markers is dropped rather than arbitrated.
 */
export const BIOMARKER_ALIASES: Record<string, string> = {
  'a g ratio': 'ag_ratio',
  'ag ratio': 'ag_ratio',
  'albumin globulin ratio': 'ag_ratio',
  'albumin globulin ratio calc': 'ag_ratio',
  alb: 'albumin',
  'serum albumin': 'albumin',
  'alk phos': 'alp',
  'alkaline phos': 'alp',
  'alkaline phosphatase alp': 'alp',
  'alkaline phosphatase s': 'alp',
  alkp: 'alp',
  'alanine aminotransferase': 'alt',
  'alanine aminotransferase alt': 'alt',
  'alanine aminotransferase sgpt': 'alt',
  'alanine transaminase': 'alt',
  'alt sgpt': 'alt',
  sgpt: 'alt',
  'sgpt alt': 'alt',
  ag: 'anion_gap',
  'anion gap': 'anion_gap',
  'anion gap calc': 'anion_gap',
  'anion gap calculated': 'anion_gap',
  'apo a 1': 'apoa1',
  'apo a1': 'apoa1',
  apoa1: 'apoa1',
  'apolipoprotein a 1': 'apoa1',
  'apolipoprotein a i': 'apoa1',
  'apolipoprotein a1': 'apoa1',
  'apo b': 'apob',
  'apo b 100': 'apob',
  'apolipoprotein b': 'apob',
  'apolipoprotein b 100': 'apob',
  'apolipoprotein b apob': 'apob',
  'apo b apo a 1 ratio': 'apob_apoa1_ratio',
  'apob apoa1': 'apob_apoa1_ratio',
  'apob apoa1 ratio': 'apob_apoa1_ratio',
  'apolipoprotein b a 1 ratio': 'apob_apoa1_ratio',
  'aspartate aminotransferase': 'ast',
  'aspartate aminotransferase ast': 'ast',
  'aspartate transaminase': 'ast',
  'ast sgot': 'ast',
  sgot: 'ast',
  'sgot ast': 'ast',
  'absolute basophil count': 'basophils_abs',
  'basophils absolute': 'basophils_abs',
  'basos abs': 'basophils_abs',
  '% basophils': 'basophils_pct',
  basophils: 'basophils_pct',
  'basophils %': 'basophils_pct',
  'basophils percent': 'basophils_pct',
  basos: 'basophils_pct',
  'bilirubin conjugated': 'bilirubin_direct',
  'bilirubin direct': 'bilirubin_direct',
  'conjugated bilirubin': 'bilirubin_direct',
  'd bili': 'bilirubin_direct',
  dbil: 'bilirubin_direct',
  'direct bilirubin': 'bilirubin_direct',
  'bilirubin indirect': 'bilirubin_indirect',
  'bilirubin indirect calc': 'bilirubin_indirect',
  'bilirubin unconjugated': 'bilirubin_indirect',
  'i bili': 'bilirubin_indirect',
  'indirect bilirubin': 'bilirubin_indirect',
  'unconjugated bilirubin': 'bilirubin_indirect',
  bilirubin: 'bilirubin_total',
  't bili': 'bilirubin_total',
  tbil: 'bilirubin_total',
  'blood urea nitrogen': 'bun',
  'bun urea nitrogen': 'bun',
  'urea nitrogen': 'bun',
  'urea nitrogen bun': 'bun',
  'bun cr': 'bun_creatinine_ratio',
  'bun creat ratio': 'bun_creatinine_ratio',
  'bun creatinine ratio': 'bun_creatinine_ratio',
  'urea nitrogen creatinine ratio': 'bun_creatinine_ratio',
  'c peptide': 'c_peptide',
  'connecting peptide': 'c_peptide',
  ca: 'calcium',
  'calcium ca': 'calcium',
  'total calcium': 'calcium',
  'adjusted calcium': 'calcium_corrected',
  'calcium albumin corrected': 'calcium_corrected',
  'calcium corrected for albumin': 'calcium_corrected',
  'corrected calcium': 'calcium_corrected',
  'corrected calcium calc': 'calcium_corrected',
  'ca ionized': 'calcium_ionized',
  'calcium ionized': 'calcium_ionized',
  'free calcium': 'calcium_ionized',
  ica: 'calcium_ionized',
  'ionized calcium': 'calcium_ionized',
  'chloride cl': 'chloride',
  'chloride ser': 'chloride',
  cl: 'chloride',
  'chol hdl ratio': 'chol_hdl_ratio',
  'chol hdlc ratio': 'chol_hdl_ratio',
  'cholesterol hdl ratio': 'chol_hdl_ratio',
  'tc hdl ratio': 'chol_hdl_ratio',
  'total chol hdl ratio': 'chol_hdl_ratio',
  'total cholesterol hdl ratio': 'chol_hdl_ratio',
  bicarbonate: 'co2',
  'carbon dioxide': 'co2',
  'carbon dioxide co2': 'co2',
  'carbon dioxide total': 'co2',
  'co2 content': 'co2',
  'co2 total': 'co2',
  hco3: 'co2',
  'total co2': 'co2',
  copper: 'copper',
  cu: 'copper',
  'cortisol morning': 'cortisol',
  'cortisol total': 'cortisol',
  'total cortisol': 'cortisol',
  creat: 'creatinine',
  'creatinine ser': 'creatinine',
  'creatinine with egfr': 'creatinine',
  'serum creatinine': 'creatinine',
  'c reactive protein': 'crp',
  'c reactive protein crp': 'crp',
  crp: 'crp',
  'crp quantitative': 'crp',
  'cystatin c with egfr': 'cystatin_c',
  dehydroepiandrosterone: 'dhea',
  dhea: 'dhea',
  'dhea lc ms ms': 'dhea',
  'dhea unconjugated': 'dhea',
  'dehydroepiandrosterone sulfate': 'dhea_s',
  'dhea so4': 'dhea_s',
  'dhea sulfate': 'dhea_s',
  dheas: 'dhea_s',
  '5 alpha dihydrotestosterone': 'dht',
  dht: 'dht',
  'dht lc ms ms': 'dht',
  dihydrotestosterone: 'dht',
  'dihydrotestosterone dht': 'dht',
  'egfr 2021 ckd epi': 'egfr',
  'egfr african american': 'egfr',
  'egfr ckd epi': 'egfr',
  'egfr creatinine based': 'egfr',
  'egfr non afr american': 'egfr',
  'estimated gfr': 'egfr',
  'estimated glomerular filtration rate': 'egfr',
  'gfr calc non af amer': 'egfr',
  'gfr est': 'egfr',
  'gfr estimated': 'egfr',
  'absolute eosinophil count': 'eosinophils_abs',
  'eos abs': 'eosinophils_abs',
  'eosinophils absolute': 'eosinophils_abs',
  '% eosinophils': 'eosinophils_pct',
  eos: 'eosinophils_pct',
  eosinophils: 'eosinophils_pct',
  'eosinophils %': 'eosinophils_pct',
  'eosinophils percent': 'eosinophils_pct',
  'erythrocyte sedimentation rate': 'esr',
  esr: 'esr',
  'esr westergren': 'esr',
  'sed rate': 'esr',
  'sed rate by modified westergren': 'esr',
  'sedimentation rate': 'esr',
  'sedimentation rate westergren': 'esr',
  eag: 'estimated_avg_glucose',
  'est average glucose': 'estimated_avg_glucose',
  'estimated average glucose': 'estimated_avg_glucose',
  'estimated average glucose eag': 'estimated_avg_glucose',
  'mean plasma glucose': 'estimated_avg_glucose',
  '17 beta estradiol': 'estradiol',
  e2: 'estradiol',
  'estradiol e2': 'estradiol',
  'estradiol lc ms ms': 'estradiol',
  'estradiol sensitive': 'estradiol',
  'estradiol sensitive lc ms': 'estradiol',
  'estradiol ultrasensitive lc ms': 'estradiol',
  e1: 'estrone',
  estrone: 'estrone',
  'estrone e1': 'estrone',
  'estrone lc ms ms': 'estrone',
  'blood glucose': 'fasting_glucose',
  'fasting blood glucose': 'fasting_glucose',
  fbg: 'fasting_glucose',
  glu: 'fasting_glucose',
  glucose: 'fasting_glucose',
  'glucose fasting': 'fasting_glucose',
  insulin: 'fasting_insulin',
  'insulin fasting': 'fasting_insulin',
  'insulin level': 'fasting_insulin',
  ferr: 'ferritin',
  'serum ferritin': 'ferritin',
  'fibrinogen activity': 'fibrinogen',
  'fibrinogen antigen': 'fibrinogen',
  'folate folic acid': 'folate',
  'folic acid': 'folate',
  'serum folate': 'folate',
  'erythrocyte folate': 'folate_rbc',
  'folate rbc': 'folate_rbc',
  'folate red blood cell': 'folate_rbc',
  'rbc folate': 'folate_rbc',
  'red blood cell folate': 'folate_rbc',
  'free t3 ft3': 'free_t3',
  'free triiodothyronine': 'free_t3',
  ft3: 'free_t3',
  't3 free': 'free_t3',
  'triiodothyronine free': 'free_t3',
  'triiodothyronine t3 free': 'free_t3',
  'free t4 ft4': 'free_t4',
  'free thyroxine': 'free_t4',
  'free thyroxine ft4': 'free_t4',
  ft4: 'free_t4',
  't4 free': 'free_t4',
  't4 free direct': 'free_t4',
  'thyroxine free': 'free_t4',
  'thyroxine t4 free': 'free_t4',
  'free t4 index': 'free_t4_index',
  'free t4 index t7': 'free_t4_index',
  'free thyroxine index': 'free_t4_index',
  fti: 'free_t4_index',
  t7: 'free_t4_index',
  'follicle stimulating hormone': 'fsh',
  'follicle stimulating hormone fsh': 'fsh',
  follitropin: 'fsh',
  fsh: 'fsh',
  'gamma glutamyl transferase': 'ggt',
  'gamma glutamyl transferase ggt': 'ggt',
  'gamma glutamyl transpeptidase': 'ggt',
  'gamma gt': 'ggt',
  ggtp: 'ggt',
  globulin: 'globulin',
  'globulin calc': 'globulin',
  'globulin calculated': 'globulin',
  'globulin total': 'globulin',
  'total globulin': 'globulin',
  a1c: 'hba1c',
  'a1c hemoglobin': 'hba1c',
  'glycated hemoglobin': 'hba1c',
  glycohemoglobin: 'hba1c',
  'glycohemoglobin a1c': 'hba1c',
  'glycosylated hemoglobin': 'hba1c',
  'hemoglobin a1c': 'hba1c',
  'hemoglobin a1c glycohemoglobin': 'hba1c',
  'hemoglobin a1c hba1c': 'hba1c',
  'hgb a1c': 'hba1c',
  hgba1c: 'hba1c',
  'cholesterol hdl': 'hdl_c',
  hdl: 'hdl_c',
  'hdl chol': 'hdl_c',
  hdlc: 'hdl_c',
  'high density lipoprotein cholesterol': 'hdl_c',
  'hdl p': 'hdl_particle_number',
  'hdl p total': 'hdl_particle_number',
  'hdl particle number': 'hdl_particle_number',
  'total hdl particles': 'hdl_particle_number',
  haematocrit: 'hematocrit',
  hct: 'hematocrit',
  'hematocrit hct': 'hematocrit',
  'packed cell volume': 'hematocrit',
  pcv: 'hematocrit',
  haemoglobin: 'hemoglobin',
  hb: 'hemoglobin',
  'hemoglobin hgb': 'hemoglobin',
  hgb: 'hemoglobin',
  'total hemoglobin': 'hemoglobin',
  'homa2 ir': 'homa_ir',
  'homeostatic model assessment ir': 'homa_ir',
  'insulin resistance score homa ir': 'homa_ir',
  hcy: 'homocysteine',
  'homocyst e ine': 'homocysteine',
  'total homocysteine': 'homocysteine',
  'c reactive protein cardiac': 'hs_crp',
  'c reactive protein high sensitivity': 'hs_crp',
  'cardiac crp': 'hs_crp',
  'crp cardiac': 'hs_crp',
  'crp high sensitivity': 'hs_crp',
  'crp hs': 'hs_crp',
  'high sensitivity c reactive protein': 'hs_crp',
  'high sensitivity crp': 'hs_crp',
  'hs c reactive protein': 'hs_crp',
  hscrp: 'hs_crp',
  'ultra sensitive crp': 'hs_crp',
  'igf 1 lc ms': 'igf_1',
  'igf i': 'igf_1',
  'insulin like growth factor 1': 'igf_1',
  'insulin like growth factor i igf 1': 'igf_1',
  'somatomedin c': 'igf_1',
  fe: 'iron',
  'iron fe': 'iron',
  'serum iron': 'iron',
  'total iron': 'iron',
  'cholesterol ldl': 'ldl_c',
  ldl: 'ldl_c',
  'ldl calc': 'ldl_c',
  'ldl calculated': 'ldl_c',
  'ldl chol': 'ldl_c',
  'ldl chol calc nih': 'ldl_c',
  'ldl cholesterol calc': 'ldl_c',
  'ldl cholesterol calc nih equation': 'ldl_c',
  'ldl cholesterol calculated': 'ldl_c',
  'low density lipoprotein cholesterol': 'ldl_c',
  'cholesterol ldl direct': 'ldl_c_direct',
  'direct ldl': 'ldl_c_direct',
  'direct ldl cholesterol': 'ldl_c_direct',
  'ldl c direct': 'ldl_c_direct',
  'ldl cholesterol direct': 'ldl_c_direct',
  'ldl direct': 'ldl_c_direct',
  'ldl p': 'ldl_particle_number',
  'ldl p particle number': 'ldl_particle_number',
  'ldl particle concentration': 'ldl_particle_number',
  'ldl particles': 'ldl_particle_number',
  'ldl particle size': 'ldl_size',
  'ldl pattern': 'ldl_size',
  'ldl peak size': 'ldl_size',
  'ldl size': 'ldl_size',
  'mean ldl size': 'ldl_size',
  lh: 'lh',
  'luteinizing hormone': 'lh',
  'luteinizing hormone lh': 'lh',
  'lipoprotein insulin resistance score': 'lipoprotein_insulin_resistance',
  'lp ir': 'lipoprotein_insulin_resistance',
  'lp ir score': 'lipoprotein_insulin_resistance',
  'lipoprotein a mass': 'lp_a',
  'lipoprotein a molar': 'lp_a',
  'lipoprotein little a': 'lp_a',
  'lp a mass': 'lp_a',
  'lp a p': 'lp_a',
  lpa: 'lp_a',
  'absolute lymphocyte count': 'lymphocytes_abs',
  alc: 'lymphocytes_abs',
  'lymphs abs': 'lymphocytes_abs',
  '% lymphocytes': 'lymphocytes_pct',
  'lymphocyte %': 'lymphocytes_pct',
  lymphocytes: 'lymphocytes_pct',
  'lymphocytes %': 'lymphocytes_pct',
  'lymphocytes percent': 'lymphocytes_pct',
  lymphs: 'lymphocytes_pct',
  magnesium: 'magnesium',
  'magnesium mg': 'magnesium',
  'magnesium ser': 'magnesium',
  mg: 'magnesium',
  'serum magnesium': 'magnesium',
  'intracellular magnesium': 'magnesium_rbc',
  'magnesium red blood cell': 'magnesium_rbc',
  'rbc magnesium': 'magnesium_rbc',
  'red blood cell magnesium': 'magnesium_rbc',
  mch: 'mch',
  'mch mean corpuscular hemoglobin': 'mch',
  'mean cell hemoglobin': 'mch',
  'mean corpuscular hemoglobin': 'mch',
  mchc: 'mchc',
  'mean cell hemoglobin concentration': 'mchc',
  'mean corpuscular hemoglobin concentration': 'mchc',
  'mcv mean corpuscular volume': 'mcv',
  'mean cell volume': 'mcv',
  'mean corpuscular volume': 'mcv',
  'methylmalonic acid': 'methylmalonic_acid',
  mma: 'methylmalonic_acid',
  'mma quantitative': 'methylmalonic_acid',
  'absolute monocyte count': 'monocytes_abs',
  'monocytes absolute': 'monocytes_abs',
  'monos abs': 'monocytes_abs',
  '% monocytes': 'monocytes_pct',
  monocytes: 'monocytes_pct',
  'monocytes %': 'monocytes_pct',
  'monocytes percent': 'monocytes_pct',
  monos: 'monocytes_pct',
  'mean platelet volume': 'mpv',
  mpv: 'mpv',
  'neut lymph ratio': 'neutrophil_lymphocyte_ratio',
  nlr: 'neutrophil_lymphocyte_ratio',
  'absolute neutrophil count': 'neutrophils_abs',
  'absolute neutrophils': 'neutrophils_abs',
  anc: 'neutrophils_abs',
  'neut abs': 'neutrophils_abs',
  'neutrophil count absolute': 'neutrophils_abs',
  '% neutrophils': 'neutrophils_pct',
  'neutrophil %': 'neutrophils_pct',
  neutrophils: 'neutrophils_pct',
  'neutrophils %': 'neutrophils_pct',
  'neutrophils percent': 'neutrophils_pct',
  neuts: 'neutrophils_pct',
  'segmented neutrophils': 'neutrophils_pct',
  segs: 'neutrophils_pct',
  'cholesterol non hdl': 'non_hdl_c',
  'non hdl chol calc': 'non_hdl_c',
  'non hdl cholesterol calc': 'non_hdl_c',
  'o3 index': 'omega_3_index',
  'omega 3 index epa dha': 'omega_3_index',
  omegacheck: 'omega_3_index',
  'aa epa ratio': 'omega_6_omega_3_ratio',
  'arachidonic acid epa ratio': 'omega_6_omega_3_ratio',
  'omega 6 3 ratio': 'omega_6_omega_3_ratio',
  'omega 6 omega 3 ratio': 'omega_6_omega_3_ratio',
  'intact pth': 'parathyroid_hormone',
  'parathyroid hormone': 'parathyroid_hormone',
  'parathyroid hormone intact': 'parathyroid_hormone',
  'parathyroid hormone pth': 'parathyroid_hormone',
  pth: 'parathyroid_hormone',
  'pth intact': 'parathyroid_hormone',
  'inorganic phosphorus': 'phosphorus',
  phos: 'phosphorus',
  phosphate: 'phosphorus',
  'phosphorus inorganic': 'phosphorus',
  'platelets count': 'platelets',
  plt: 'platelets',
  thrombocytes: 'platelets',
  k: 'potassium',
  'potassium k': 'potassium',
  'potassium level': 'potassium',
  'potassium ser': 'potassium',
  prog: 'progesterone',
  progesterone: 'progesterone',
  'progesterone lc ms ms': 'progesterone',
  prl: 'prolactin',
  prolactin: 'prolactin',
  'prolactin prl': 'prolactin',
  'free psa': 'psa_free',
  'psa free': 'psa_free',
  'prostate specific antigen': 'psa_total',
  'prostate specific antigen psa': 'psa_total',
  psa: 'psa_total',
  'total psa': 'psa_total',
  erythrocytes: 'rbc',
  'rbc count': 'rbc',
  'rbc red blood cell': 'rbc',
  'red blood cells': 'rbc',
  'red cell count': 'rbc',
  'rdw cv': 'rdw',
  'rdw sd': 'rdw',
  'red blood cell distribution width': 'rdw',
  'red cell distribution width': 'rdw',
  'reverse t3': 'reverse_t3',
  'reverse triiodothyronine': 'reverse_t3',
  rt3: 'reverse_t3',
  't3 reverse': 'reverse_t3',
  't3 reverse lc ms ms': 'reverse_t3',
  't3 reverse rt3': 'reverse_t3',
  'triiodothyronine reverse': 'reverse_t3',
  se: 'selenium',
  selenium: 'selenium',
  'sex horm binding glob': 'shbg',
  'sex hormone binding globulin': 'shbg',
  'sex hormone binding globulin shbg': 'shbg',
  'ldl small': 'small_ldl_p',
  'ldl small particle number': 'small_ldl_p',
  'small dense ldl': 'small_ldl_p',
  'small ldl p': 'small_ldl_p',
  'small ldl particle number': 'small_ldl_p',
  na: 'sodium',
  'sodium level': 'sodium',
  'sodium na': 'sodium',
  'sodium ser': 'sodium',
  't uptake': 't3_uptake',
  't3 uptake': 't3_uptake',
  't3 uptake ratio': 't3_uptake',
  thbr: 't3_uptake',
  'thyroid hormone uptake': 't3_uptake',
  'bio t': 'testosterone_bioavailable',
  'bioavailable testosterone': 'testosterone_bioavailable',
  'bioavailable testosterone calc': 'testosterone_bioavailable',
  'testosterone bioavailable': 'testosterone_bioavailable',
  'free testosterone': 'testosterone_free',
  'free testosterone direct': 'testosterone_free',
  'free testosterone equilibrium dialysis': 'testosterone_free',
  ft: 'testosterone_free',
  'testosterone free calculated': 'testosterone_free',
  'testosterone free direct': 'testosterone_free',
  testosterone: 'testosterone_total',
  'testosterone total immunoassay': 'testosterone_total',
  'testosterone total lc ms ms': 'testosterone_total',
  'testosterone total ms': 'testosterone_total',
  'total testosterone': 'testosterone_total',
  'anti thyroglobulin': 'tg_ab',
  'antithyroglobulin antibody': 'tg_ab',
  tgab: 'tg_ab',
  'thyroglobulin ab': 'tg_ab',
  'thyroglobulin antibodies': 'tg_ab',
  'thyroglobulin antibody': 'tg_ab',
  'tg by lc ms ms': 'thyroglobulin',
  thyroglobulin: 'thyroglobulin',
  'thyroglobulin tg': 'thyroglobulin',
  'iron binding capacity tibc': 'tibc',
  'iron binding capacity total': 'tibc',
  'total iron binding capacity': 'tibc',
  chol: 'total_cholesterol',
  cholesterol: 'total_cholesterol',
  'cholesterol total': 'total_cholesterol',
  'protein total': 'total_protein',
  'total protein': 'total_protein',
  tp: 'total_protein',
  t3: 'total_t3',
  't3 total': 'total_t3',
  'total t3': 'total_t3',
  'total triiodothyronine': 'total_t3',
  'triiodothyronine t3': 'total_t3',
  'triiodothyronine t3 total': 'total_t3',
  'triiodothyronine total': 'total_t3',
  t4: 'total_t4',
  't4 total': 'total_t4',
  'thyroxine t4': 'total_t4',
  'thyroxine t4 total': 'total_t4',
  'thyroxine total': 'total_t4',
  'total t4': 'total_t4',
  'total thyroxine': 'total_t4',
  'anti thyroid peroxidase antibody': 'tpo_ab',
  'anti tpo': 'tpo_ab',
  'thyroid peroxidase antibodies': 'tpo_ab',
  'thyroid peroxidase tpo ab': 'tpo_ab',
  'thyroperoxidase ab': 'tpo_ab',
  tpoab: 'tpo_ab',
  siderophilin: 'transferrin',
  transferrin: 'transferrin',
  '% iron saturation': 'transferrin_saturation',
  '% sat': 'transferrin_saturation',
  '% saturation': 'transferrin_saturation',
  '% transferrin saturation': 'transferrin_saturation',
  'iron sat': 'transferrin_saturation',
  'iron saturation': 'transferrin_saturation',
  'iron saturation %': 'transferrin_saturation',
  'saturation iron': 'transferrin_saturation',
  'transferrin saturation calc': 'transferrin_saturation',
  trig: 'triglycerides',
  triglyceride: 'triglycerides',
  'triglycerides fasting': 'triglycerides',
  'triglycerides trig': 'triglycerides',
  trigs: 'triglycerides',
  'thyroid stimulating hormone': 'tsh',
  thyrotropin: 'tsh',
  'tsh 3rd generation': 'tsh',
  'tsh thyroid stimulating hormone': 'tsh',
  'tsh w reflex to ft4': 'tsh',
  'ultrasensitive tsh': 'tsh',
  'acr urine': 'uacr',
  'albumin creatinine ratio urine': 'uacr',
  'microalbumin creatinine ratio': 'uacr',
  'microalbumin creatinine ratio urine': 'uacr',
  uacr: 'uacr',
  'urine albumin creatinine ratio': 'uacr',
  uibc: 'uibc',
  'unsaturated iron binding capacity': 'uibc',
  'unsaturated iron binding capacity uibc': 'uibc',
  urate: 'uric_acid',
  uric: 'uric_acid',
  retinol: 'vitamin_a',
  'vitamin a': 'vitamin_a',
  'vitamin a retinol': 'vitamin_a',
  thiamin: 'vitamin_b1',
  thiamine: 'vitamin_b1',
  'vitamin b1': 'vitamin_b1',
  'vitamin b1 thiamine': 'vitamin_b1',
  b12: 'vitamin_b12',
  cobalamin: 'vitamin_b12',
  cyanocobalamin: 'vitamin_b12',
  'vit b12': 'vitamin_b12',
  'vitamin b 12': 'vitamin_b12',
  'vitamin b12 cobalamin': 'vitamin_b12',
  p5p: 'vitamin_b6',
  'pyridoxal 5 phosphate': 'vitamin_b6',
  'pyridoxal 5 phosphate plp': 'vitamin_b6',
  pyridoxine: 'vitamin_b6',
  'vitamin b 6': 'vitamin_b6',
  'vitamin b6': 'vitamin_b6',
  ascorbate: 'vitamin_c',
  'ascorbic acid': 'vitamin_c',
  'vitamin c': 'vitamin_c',
  'vitamin c ascorbic acid': 'vitamin_c',
  '25 hydroxy vitamin d': 'vitamin_d',
  '25 hydroxyvitamin d': 'vitamin_d',
  '25 oh d': 'vitamin_d',
  '25 oh vit d total': 'vitamin_d',
  '25 oh vitamin d': 'vitamin_d',
  calcidiol: 'vitamin_d',
  'vit d 25 oh': 'vitamin_d',
  'vitamin d 25 hydroxy': 'vitamin_d',
  'vitamin d 25 hydroxy total': 'vitamin_d',
  'vitamin d 25 oh total': 'vitamin_d',
  '1 25 dihydroxy vitamin d': 'vitamin_d_1_25',
  '1 25 dihydroxyvitamin d': 'vitamin_d_1_25',
  '1 25 oh 2 vitamin d': 'vitamin_d_1_25',
  '1 25 oh2 vitamin d': 'vitamin_d_1_25',
  calcitriol: 'vitamin_d_1_25',
  'vitamin d 1 25 dihydroxy': 'vitamin_d_1_25',
  'vitamin d 1 25 dihydroxy total': 'vitamin_d_1_25',
  '25 hydroxyvitamin d2': 'vitamin_d2',
  '25 oh vitamin d2': 'vitamin_d2',
  'ergocalciferol d2': 'vitamin_d2',
  'vitamin d 25 hydroxy d2': 'vitamin_d2',
  'vitamin d2': 'vitamin_d2',
  '25 hydroxyvitamin d3': 'vitamin_d3',
  '25 oh vitamin d3': 'vitamin_d3',
  'cholecalciferol d3': 'vitamin_d3',
  'vitamin d 25 hydroxy d3': 'vitamin_d3',
  'vitamin d3': 'vitamin_d3',
  'alpha tocopherol': 'vitamin_e',
  'tocopherol alpha': 'vitamin_e',
  'vitamin e': 'vitamin_e',
  'vitamin e alpha tocopherol': 'vitamin_e',
  'cholesterol vldl': 'vldl_c',
  'vldl c': 'vldl_c',
  'vldl chol cal': 'vldl_c',
  'vldl cholesterol': 'vldl_c',
  'vldl cholesterol cal': 'vldl_c',
  'vldl cholesterol calculated': 'vldl_c',
  leukocytes: 'wbc',
  'total wbc': 'wbc',
  'wbc count': 'wbc',
  'wbc white blood cell': 'wbc',
  'white blood cells': 'wbc',
  'white cell count': 'wbc',
  zn: 'zinc',
};

/**
 * Unit pairs convertible for ANY analyte: pure decimal-prefix or volume
 * changes, plus true identities (ng/mL is ug/L, pg/mL is ng/L, uIU/mL is
 * mIU/L). No molar mass is involved, so no analyte can make one of these wrong.
 * Keyed "from|to" on normalizeUnit's output.
 *
 * Two deliberate absences:
 *   * mEq/L → mmol/L is NOT here — it is valence-dependent, so it lives per
 *     analyte (0.5 for calcium and magnesium; 1:1 for sodium and potassium).
 *   * g/dL ↔ mg/dL is NOT here. A lab reporting "albumin" in mg/dL is reporting
 *     URINE microalbumin — a different specimen, ~1000x lower — and a working
 *     conversion would invite ingesting it as serum albumin.
 */
export const UNIVERSAL_UNIT_CONVERSIONS: Record<string, number> = {
  'mg/dl|mg/l': 10,
  'mg/l|mg/dl': 0.1,
  'g/dl|g/l': 10,
  'g/l|g/dl': 0.1,
  'ng/ml|ug/l': 1,
  'ug/l|ng/ml': 1,
  'ug/dl|ng/ml': 10,
  'ng/ml|ug/dl': 0.1,
  'ng/dl|ng/ml': 0.01,
  'ng/ml|ng/dl': 100,
  'pg/ml|ng/l': 1,
  'ng/l|pg/ml': 1,
  'pg/ml|ug/l': 0.001,
  'ug/dl|ug/l': 10,
  'mmol/l|umol/l': 1000,
  'umol/l|mmol/l': 0.001,
  'umol/l|nmol/l': 1000,
  'nmol/l|umol/l': 0.001,
  'nmol/l|pmol/l': 1000,
  'pmol/l|nmol/l': 0.001,
  'uiu/ml|miu/l': 1,
  'miu/l|uiu/ml': 1,
  'iu/ml|iu/l': 1000,
};

/**
 * Mass ↔ molar conversions, which depend on the analyte's molecular weight and
 * are therefore keyed "slug|from|to". Each factor was recomputed from the
 * molecular weight and cross-checked against the published clinical value.
 *
 * Absent on purpose — refusing is the correct behavior, and a refused row
 * reaches review as a unit conflict rather than a wrong number:
 *   * **Lp(a) nmol/L ↔ mg/dL.** nmol/L counts apo(a) particles; mg/dL measures
 *     Lp(a) mass. No constant relates them — the apo(a) protein varies in size
 *     between individuals.
 *   * **Insulin uIU/mL ↔ pmol/L.** Standard-dependent (6.0 vs 6.945, ~16%
 *     apart). Picking one silently would bias every converted insulin value.
 *   * **HbA1c % ↔ mmol/mol**, which is affine ((NGSP - 2.15) x 10.929), not a
 *     multiply, so it cannot be expressed in this table at all.
 */
export const UNIT_CONVERSIONS: Record<string, number> = {
  'bilirubin_total|mg/dl|umol/l': 17.104,
  'bilirubin_total|umol/l|mg/dl': 0.058466,
  'bun|mg/dl|mmol/l': 0.356964,
  'bun|mmol/l|mg/dl': 2.8014,
  'calcium|meq/l|mmol/l': 0.5,
  'calcium|mg/dl|mmol/l': 0.249513,
  'calcium|mmol/l|mg/dl': 4.0078,
  'cortisol|nmol/l|ug/dl': 0.036246,
  'cortisol|ug/dl|nmol/l': 27.5893,
  'creatinine|mg/dl|umol/l': 88.4017,
  'creatinine|umol/l|mg/dl': 0.011312,
  'estradiol|pg/ml|pmol/l': 3.67134,
  'estradiol|pmol/l|pg/ml': 0.27238,
  'fasting_glucose|mg/dl|mmol/l': 0.055507,
  'fasting_glucose|mmol/l|mg/dl': 18.0156,
  'folate|ng/ml|nmol/l': 2.26552,
  'folate|nmol/l|ng/ml': 0.4414,
  'free_t3|pg/ml|pmol/l': 1.53615,
  'free_t3|pmol/l|pg/ml': 0.65098,
  'free_t4|ng/dl|pmol/l': 12.8722,
  'free_t4|pmol/l|ng/dl': 0.077687,
  'hdl_c|mg/dl|mmol/l': 0.025863,
  'hdl_c|mmol/l|mg/dl': 38.6654,
  'hemoglobin|g/dl|mmol/l': 0.620559,
  'hemoglobin|mmol/l|g/dl': 1.61145,
  'homocysteine|mg/l|umol/l': 7.39754,
  'homocysteine|umol/l|mg/l': 0.13518,
  'iron|ug/dl|umol/l': 0.179067,
  'iron|umol/l|ug/dl': 5.5845,
  'ldl_c|mg/dl|mmol/l': 0.025863,
  'ldl_c|mmol/l|mg/dl': 38.6654,
  'magnesium|meq/l|mmol/l': 0.5,
  'magnesium|mg/dl|mmol/l': 0.411438,
  'magnesium|mmol/l|mg/dl': 2.4305,
  'phosphorus|mg/dl|mmol/l': 0.322851,
  'phosphorus|mmol/l|mg/dl': 3.0974,
  'testosterone_total|ng/dl|nmol/l': 0.0346717,
  'testosterone_total|nmol/l|ng/dl': 28.842,
  'total_cholesterol|mg/dl|mmol/l': 0.025863,
  'total_cholesterol|mmol/l|mg/dl': 38.6654,
  'triglycerides|mg/dl|mmol/l': 0.011294,
  'triglycerides|mmol/l|mg/dl': 88.54,
  'uric_acid|mg/dl|umol/l': 59.4849,
  'uric_acid|umol/l|mg/dl': 0.016811,
  'vitamin_b12|pg/ml|pmol/l': 0.737806,
  'vitamin_b12|pmol/l|pg/ml': 1.35537,
  'vitamin_d|ng/ml|nmol/l': 2.49601,
  'vitamin_d|nmol/l|ng/ml': 0.40064,
};
